import Head from "next/head";
import { useRouter } from "next/router";
import { UserButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const router = useRouter();
  const { isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>dynolabs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        {
          isSignedIn ? (
            <UserButton />
          ) : (
            <button
              onClick={() => router.push("/sign-in")}
            >
              Sign in
            </button>
          )
        }
      </header>
    </>
  );
}
